# Only allow push + tag events
when:
  event: [push, tag]

steps:

  # ===================================================
  # 1. Build for staging (only when main is pushed)
  # ===================================================
  build-staging:
    when:
      event: push
      branch: main
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: 10.10.10.112:5000
      repo: coinluxer/clx-etl
      tags:
        - latest
        - ${CI_COMMIT_SHA:0:8}
      skip_tls_verify: true
      cache: true

  # ===================================================
  # 2. Deploy staging (only when main is pushed)
  # ===================================================
  deploy-staging:
    when:
      event: push
      branch: main
    image: alpine
    environment:
      HOST: 10.10.10.137
      REGISTRY: 10.10.10.112:5000
      IMAGE_NAME: coinluxer/clx-etl
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
      SSH_KNOWN_HOSTS:
        from_secret: SSH_KNOWN_HOSTS
      DORIS_PASSWORD:
        from_secret: DORIS_PASSWORD_STG
      MYSQL_PASSWORD:
        from_secret: MYSQL_PASSWORD_STG
    commands:
      - apk add openssh-client docker-cli
      - mkdir -p ~/.ssh
      - printf "%s" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - printf "%s" "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      - |
          ssh -o StrictHostKeyChecking=yes hhe@$HOST "
            set -xe;

            docker pull $REGISTRY/$IMAGE_NAME:${CI_COMMIT_SHA:0:8};
            docker stop clx-etl || true;
            docker rm clx-etl || true;
            
            docker run -d \
              --name clx-etl \
              --restart always \
              -e ENV=staging \
              -e DORIS_HOST=192.168.50.136 \
              -e DORIS_HTTP_PORT=8030 \
              -e DORIS_PORT=9030 \
              -e DORIS_USER=etl \
              -e DORIS_PASSWORD=$DORIS_PASSWORD \
              -e DORIS_DB=clx_stg \
              -e MYSQL_HOST=192.168.50.137 \
              -e MYSQL_PORT=3306 \
              -e MYSQL_USER=etl \
              -e MYSQL_PASSWORD=$MYSQL_PASSWORD \
              -e MYSQL_DB=clx_stg \
              $REGISTRY/$IMAGE_NAME:${CI_COMMIT_SHA:0:8};
          "

  # ===================================================
  # 3. Build production image when TAG is created
  # ===================================================
  build-production:
    when:
      event: tag
      branch: main
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: 10.10.10.112:5000
      repo: 10.10.10.112:5000/coinluxer/clx-etl
      tags:
        - ${CI_COMMIT_TAG}       # <-- v1.0.0
      skip_tls_verify: true
      cache: true

  # ===================================================
  # 4. Deploy production only when tag in main
  # ===================================================
  deploy-production:
    when:
      event: tag
      branch: main
    image: alpine
    environment:
      HOST: 10.10.10.132
      REGISTRY: 10.10.10.112:5000
      IMAGE_NAME: coinluxer/clx-etl
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
      SSH_KNOWN_HOSTS:
        from_secret: SSH_KNOWN_HOSTS
      DORIS_PASSWORD:
        from_secret: DORIS_PASSWORD_PROD
      MYSQL_PASSWORD:
        from_secret: MYSQL_PASSWORD_PROD
    commands:
      - apk add openssh-client docker-cli
      - mkdir -p ~/.ssh
      - printf "%s" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - printf "%s" "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      - |
          ssh -o StrictHostKeyChecking=yes hhe@$HOST "
            set -xe;

            docker pull $REGISTRY/$IMAGE_NAME:${CI_COMMIT_TAG};
            docker stop clx-etl || true;
            docker rm clx-etl || true;

            docker run -d \
              --name clx-etl \
              --restart always \
              -e ENV=production \
              -e DORIS_HOST=192.168.50.131 \
              -e DORIS_HTTP_PORT=8030 \
              -e DORIS_PORT=9030 \
              -e DORIS_USER=etl \
              -e DORIS_PASSWORD=$DORIS_PASSWORD \
              -e DORIS_DB=coinluxer \
              -e MYSQL_HOST=192.168.50.132 \
              -e MYSQL_PORT=3306 \
              -e MYSQL_USER=etl \
              -e MYSQL_PASSWORD=$MYSQL_PASSWORD \
              -e MYSQL_DB=coinluxer \
              $REGISTRY/$IMAGE_NAME:${CI_COMMIT_TAG};
          "
